// Autogenerated from Pigeon (v1.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}

@interface EJPurchaseModel ()
+ (EJPurchaseModel *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation EJPurchaseModel
+ (EJPurchaseModel *)fromMap:(NSDictionary *)dict {
  EJPurchaseModel *result = [[EJPurchaseModel alloc] init];
  result.isPurchase = dict[@"isPurchase"];
  if ((NSNull *)result.isPurchase == [NSNull null]) {
    result.isPurchase = nil;
  }
  return result;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.isPurchase ? self.isPurchase : [NSNull null]), @"isPurchase", nil];
}
@end

@interface EJPurchaseModelApiCodecReader : FlutterStandardReader
@end
@implementation EJPurchaseModelApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [EJPurchaseModel fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface EJPurchaseModelApiCodecWriter : FlutterStandardWriter
@end
@implementation EJPurchaseModelApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[EJPurchaseModel class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface EJPurchaseModelApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation EJPurchaseModelApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[EJPurchaseModelApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[EJPurchaseModelApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *EJPurchaseModelApiGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    EJPurchaseModelApiCodecReaderWriter *readerWriter = [[EJPurchaseModelApiCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void EJPurchaseModelApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<EJPurchaseModelApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.PurchaseModelApi.getPurchaseModel"
        binaryMessenger:binaryMessenger
        codec:EJPurchaseModelApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getPurchaseModelWithError:)], @"EJPurchaseModelApi api (%@) doesn't respond to @selector(getPurchaseModelWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        EJPurchaseModel *output = [api getPurchaseModelWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
