// Autogenerated from Pigeon (v1.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class EJVersion;

@interface EJVersion : NSObject
@property(nonatomic, copy, nullable) NSString * string;
@end

/// The codec used by EJPlatformVersionApi.
NSObject<FlutterMessageCodec> *EJPlatformVersionApiGetCodec(void);

@protocol EJPlatformVersionApi
- (nullable EJVersion *)getPlatformVersionWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void EJPlatformVersionApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<EJPlatformVersionApi> *_Nullable api);

NS_ASSUME_NONNULL_END
