// Autogenerated from Pigeon (v1.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class EJPurchaseModel;

@interface EJPurchaseModel : NSObject
@property(nonatomic, strong, nullable) NSNumber * isPurchase;
@end

/// The codec used by EJPurchaseModelApi.
NSObject<FlutterMessageCodec> *EJPurchaseModelApiGetCodec(void);

@protocol EJPurchaseModelApi
- (nullable EJPurchaseModel *)getPurchaseModelWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void EJPurchaseModelApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<EJPurchaseModelApi> *_Nullable api);

NS_ASSUME_NONNULL_END
