// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgBPkVRQ-RaMvIbgZzBrPQPHyl8MVBhzU',
    appId: '1:569212364150:web:8aae4e06e58c22c2a70657',
    messagingSenderId: '569212364150',
    projectId: 'estatjapan-4a8ac',
    authDomain: 'estatjapan-4a8ac.firebaseapp.com',
    storageBucket: 'estatjapan-4a8ac.appspot.com',
    measurementId: 'G-0R3G2G2TF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDfor1WJtPJ8WXUg9UWNZd5EO7EHY94Iw',
    appId: '1:569212364150:android:4eff6beed32a316aa70657',
    messagingSenderId: '569212364150',
    projectId: 'estatjapan-4a8ac',
    storageBucket: 'estatjapan-4a8ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoWTFuLlwUaaFSjduzcGpWz1Zx1xx4Ras',
    appId: '1:569212364150:ios:61e43ce6802185d3a70657',
    messagingSenderId: '569212364150',
    projectId: 'estatjapan-4a8ac',
    storageBucket: 'estatjapan-4a8ac.appspot.com',
    iosClientId: '569212364150-ugocfgvoi2esplaqkbh67h4nhgkus3q9.apps.googleusercontent.com',
    iosBundleId: 'com.estatjapan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoWTFuLlwUaaFSjduzcGpWz1Zx1xx4Ras',
    appId: '1:569212364150:ios:844a6931c10e7b4da70657',
    messagingSenderId: '569212364150',
    projectId: 'estatjapan-4a8ac',
    storageBucket: 'estatjapan-4a8ac.appspot.com',
    iosClientId: '569212364150-7sf4r01lg8fd7dq5vt0uj0tkshog3s66.apps.googleusercontent.com',
    iosBundleId: 'com.estatjapan.estatjapan',
  );
}
