// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMuvQN3Zf3GX9tXXEJo4Mmdllwq6QBlxw',
    appId: '1:327810721125:web:94928e2a34ad7ef2f3ad8c',
    messagingSenderId: '327810721125',
    projectId: 'estatjapan-e3be3',
    authDomain: 'estatjapan-e3be3.firebaseapp.com',
    storageBucket: 'estatjapan-e3be3.appspot.com',
    measurementId: 'G-561YN3ZGTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYUzCNCesAaUcG8N9dUuY9HIEBncp_LUA',
    appId: '1:327810721125:android:d252af54007f800cf3ad8c',
    messagingSenderId: '327810721125',
    projectId: 'estatjapan-e3be3',
    storageBucket: 'estatjapan-e3be3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlgS9aJLefDL3-NoK9MOXZV2sc_TVvVho',
    appId: '1:327810721125:ios:6c91c3a4197241fdf3ad8c',
    messagingSenderId: '327810721125',
    projectId: 'estatjapan-e3be3',
    storageBucket: 'estatjapan-e3be3.appspot.com',
    iosClientId: '327810721125-v8peg5tpmfdft90j7e4rucaj4clrv3ak.apps.googleusercontent.com',
    iosBundleId: 'com.estatjapan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlgS9aJLefDL3-NoK9MOXZV2sc_TVvVho',
    appId: '1:327810721125:ios:131c223f18ab8506f3ad8c',
    messagingSenderId: '327810721125',
    projectId: 'estatjapan-e3be3',
    storageBucket: 'estatjapan-e3be3.appspot.com',
    iosClientId: '327810721125-sbeslrq1hbs00q37e20bvko7q4a7j55h.apps.googleusercontent.com',
    iosBundleId: 'com.estatjapan.estatjapan',
  );
}
